default: false
description: Pass build environment variables into Dockerfile builds as build arguments.
id: dockerfile_inject_env_variables
label: Inject environment variables in Dockerfile
show_when:
  build_type: dockerfile
type: boolean
