cpu: >-
  << string(module.input.capacity_provider == "ec2" ? int(float(module.input.task_cpu) * 1024) :
  int(float(module.input.fargate_size.vcpu) * 1024)) >>
execution_role_arn: <<stack.output.execution_role_arn>>
family: <<stack.output.task_definition_family>>
memory: >-
  << string(module.input.capacity_provider == "ec2" ? int(float(module.input.task_memory) * 1024) :
  int(float(module.input.fargate_size.memory_gb) * 1024)) >>
ephemeral_storage: >-
  << module.input.capacity_provider != "ec2" && module.input.task_ephemeral_storage_size_gib ? {size_in_gib:
  module.input.task_ephemeral_storage_size_gib} : nil >>
network_mode: awsvpc
requires_compatibilities: '<< module.input.capacity_provider == "ec2" ? ["EC2"] : ["FARGATE"] >>'
runtime_platform:
  cpu_architecture: <<module.input.cpu_architecture>>
  operating_system_family: LINUX
task_role_arn: <<stack.output.task_role_arn>>
volumes: >-
  << module.input.efs_enabled ? [{"name": "efs", "efs_volume_configuration": {"file_system_id":
  module.input.efs_file_system_id, "transit_encryption": "ENABLED", "authorization_config":
  (module.input.efs_access_point_id ? {"access_point_id": module.input.efs_access_point_id} : nil)}}] : [] >>
